name: Deployment
on:
  push:
    tags:
      - v*.*.*
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install Dependencies
        run: yarn install

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get package info
        id: package
        uses: rexdefuror/read-package-json@v1.0.5

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.PACKAGE_NAME }}:${{ github.ref_name }}
  
  label-closed-pr:
    runs-on: ubuntu-latest
    needs:
      - deploy
    steps:

      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          state: closed
      
      - name: Add label from closed PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            github.rest.issues.addLabels({
              issue_number: ${{ steps.findPr.outputs.pr }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["autorelease: published"]
            })
      
      - name: Remove Label to closed PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            github.rest.issues.removeLabel({
              issue_number: ${{ steps.findPr.outputs.pr }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: "autorelease: tagged"
            })