name: Release Setup
on:
  push:
    branches:
      - main
jobs:
  release-setup:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GH_TOKEN }}
          release-type: node
          package-name: exobrain-util
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false}]'